# Naive Bayes 


In [2]:
import numpy
from sklearn import datasets, metrics
from sklearn.naive_bayes import GaussianNB
X,y=datasets.load_iris(return_X_y=True)
# print(X)
# print(y)
X_train=X[range(0,150,2),:]   
y_train=y[range(0,150,2)]
X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]
clf = GaussianNB() #creating instance of a classifier #BernoulliNB() for BernouliNB
#MultinomialNB() for MultinomialNB()
clf.fit(X_train, y_train)
prediction = clf.predict(X_test) #predict using the learnt classifier
print("############### Predictions #################")
print(prediction)
print("#############################################")
print("Accuracy:",metrics.accuracy_score(y_test, prediction, normalize=True))
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

############### Predictions #################
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 2 2
 2]
#############################################
Accuracy: 0.96
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

[[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]


# Bernouli


In [23]:
import numpy
from sklearn import datasets, metrics
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd


vectorizer = CountVectorizer()

In [24]:
df = pd.read_csv('Datasets/movie_review.csv')

df.head()
df = df[]

fold_id cv_tag  html_id  sent_id  \
0        0  cv000    29590        0   
1        0  cv000    29590        1   
2        0  cv000    29590        2   
3        0  cv000    29590        3   
4        0  cv000    29590        4   

                                                text  tag  
0  films adapted from comic books have had plenty...  pos  
1  for starters , it was created by alan moore ( ...  pos  
2  to say moore and campbell thoroughly researche...  pos  
3  the book ( or " graphic novel , " if you will ...  pos  
4  in other words , don't dismiss this film becau...  pos

In [25]:
#Changing the pos to q and neg to 0 in column 'tag'

df['tag'] = df['tag'].replace(['pos','neg'],[1,0])
df.tail()

fold_id cv_tag  html_id  sent_id  \
64715        9  cv999    14636       20   
64716        9  cv999    14636       21   
64717        9  cv999    14636       22   
64718        9  cv999    14636       23   
64719        9  cv999    14636       24   

                                                    text  tag  
64715  that lack of inspiration can be traced back to...    0  
64716  like too many of the skits on the current inca...    0  
64717  after watching one of the " roxbury " skits on...    0  
64718   bump unsuspecting women , and . . . that's all .    0  
64719  after watching _a_night_at_the_roxbury_ , you'...    0

In [28]:
#Deleting the extra columns

df.drop(['fold_id','cv_tag','html_id','sent_id'], axis =1, inplace = True)

In [29]:
df.head()

text  tag
0  films adapted from comic books have had plenty...    1
1  for starters , it was created by alan moore ( ...    1
2  to say moore and campbell thoroughly researche...    1
3  the book ( or " graphic novel , " if you will ...    1
4  in other words , don't dismiss this film becau...    1

In [30]:
df.tail()

text  tag
64715  that lack of inspiration can be traced back to...    0
64716  like too many of the skits on the current inca...    0
64717  after watching one of the " roxbury " skits on...    0
64718   bump unsuspecting women , and . . . that's all .    0
64719  after watching _a_night_at_the_roxbury_ , you'...    0

In [31]:
docs = []
for row in range(0,len(df.index)):
    docs.append(''.join(str(x) for x in df.iloc[row,0]))
    

In [32]:
  
vectorizer.fit(docs) 
  
# Printing the identified Unique words along with their indices 
print("Vocabulary: ", vectorizer.vocabulary_) 
  
# Encode the Document 
vector = vectorizer.transform(docs) 
  
# Summarizing the Encoded Texts 
print("Encoded Document is:") 
array = vector.toarray()
print(array)



Vocabulary:  {'films': 13196, 'adapted': 1014, 'from': 14073, 'comic': 7039, 'books': 4366, 'have': 16028, 'had': 15656, 'plenty': 26439, 'of': 24386, 'success': 34108, 'whether': 38707, 'they': 35351, 're': 28303, 'about': 750, 'superheroes': 34291, 'batman': 3308, 'superman': 34299, 'spawn': 32906, 'or': 24635, 'geared': 14473, 'toward': 35949, 'kids': 19446, 'casper': 5688, 'the': 35280, 'arthouse': 2359, 'crowd': 8360, 'ghost': 14650, 'world': 39165, 'but': 5187, 'there': 35324, 'never': 23719, 'really': 28357, 'been': 3486, 'book': 4357, 'like': 20492, 'hell': 16247, 'before': 3503, 'for': 13695, 'starters': 33420, 'it': 18630, 'was': 38405, 'created': 8187, 'by': 5224, 'alan': 1408, 'moore': 22910, 'and': 1810, 'eddie': 11120, 'campbell': 5395, 'who': 38781, 'brought': 4875, 'medium': 22042, 'to': 35714, 'whole': 38791, 'new': 23726, 'level': 20347, 'in': 17608, 'mid': 22336, '80s': 403, 'with': 39013, '12': 37, 'part': 25408, 'series': 31231, 'called': 5339, 'watchmen': 38438, '

Encoded Document is:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [33]:
col_list = [[None] for i in range(0,len(vectorizer.vocabulary_ ) )]


doc_dict = vectorizer.vocabulary_
for key in doc_dict:
    col_list[doc_dict[key]] = key
col_list



['00',
 '000',
 '0009f',
 '007',
 '00s',
 '03',
 '04',
 '05',
 '05425',
 '10',
 '100',
 '1000',
 '10000',
 '100m',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '10b',
 '10s',
 '10th',
 '11',
 '110',
 '111',
 '112',
 '113',
 '1138',
 '114',
 '115',
 '117',
 '118',
 '11th',
 '12',
 '121',
 '122',
 '123',
 '125',
 '126',
 '127',
 '1272',
 '128',
 '129',
 '1298',
 '12th',
 '13',
 '130',
 '1305',
 '131',
 '132',
 '133',
 '135',
 '137',
 '138',
 '139',
 '13th',
 '14',
 '140',
 '1400',
 '143',
 '144',
 '14th',
 '15',
 '150',
 '1500s',
 '150th',
 '151',
 '152',
 '1521',
 '153',
 '155',
 '1554',
 '157',
 '1583',
 '1590',
 '15th',
 '16',
 '160',
 '1600',
 '1600s',
 '161',
 '165',
 '167',
 '1692',
 '16mm',
 '16th',
 '16x9',
 '17',
 '170',
 '1700s',
 '1709',
 '172',
 '175',
 '1773',
 '1791',
 '1792',
 '1793',
 '1794',
 '1799',
 '17th',
 '18',
 '180',
 '1800',
 '1800s',
 '1812',
 '1830s',
 '1839',
 '1847',
 '1862',
 '1865',
 '1869',
 '1871',
 '1885',
 '1888',
 '189',
 '1

In [39]:
tempDf = pd.DataFrame(data = array,columns=col_list)
tempDf.head()

00  000  0009f  007  00s  03  04  05  05425  10  ...  zukovsky  zulu  \
0   0    0      0    0    0   0   0   0      0   0  ...         0     0   
1   0    0      0    0    0   0   0   0      0   0  ...         0     0   
2   0    0      0    0    0   0   0   0      0   0  ...         0     0   
3   0    0      0    0    0   0   0   0      0   0  ...         0     0   
4   0    0      0    0    0   0   0   0      0   0  ...         0     0   

   zundel  zurg  zus  zweibel  zwick  zwigoff  zycie  zzzzzzz  
0       0     0    0        0      0        0      0        0  
1       0     0    0        0      0        0      0        0  
2       0     0    0        0      0        0      0        0  
3       0     0    0        0      0        0      0        0  
4       0     0    0        0      0        0      0        0  

[5 rows x 39659 columns]

In [40]:
tempDf['00tag'] = df['tag']

In [49]:
tempDf.head()

00  000  0009f  007  00s  03  04  05  05425  10  ...  zulu  zundel  zurg  \
0   0    0      0    0    0   0   0   0      0   0  ...     0       0     0   
1   0    0      0    0    0   0   0   0      0   0  ...     0       0     0   
2   0    0      0    0    0   0   0   0      0   0  ...     0       0     0   
3   0    0      0    0    0   0   0   0      0   0  ...     0       0     0   
4   0    0      0    0    0   0   0   0      0   0  ...     0       0     0   

   zus  zweibel  zwick  zwigoff  zycie  zzzzzzz  00tag  
0    0        0      0        0      0        0      0  
1    0        0      0        0      0        0      0  
2    0        0      0        0      0        0      0  
3    0        0      0        0      0        0      0  
4    0        0      0        0      0        0      0  

[5 rows x 39660 columns]

In [51]:
len(tempDf[tempDf['00tag'] == 0])

MemoryError: Unable to allocate 19.1 GiB for an array with shape (39660, 64720) and data type int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3) 

In [ ]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()

In [27]:
import numpy as np
rng = np.random.RandomState(1)
X = rng.randint(5, size=(6, 100))
X

array([[3, 4, 0, 1, 3, 0, 0, 1, 4, 4, 1, 2, 4, 2, 4, 3, 4, 2, 4, 2, 4, 1,
        1, 0, 1, 1, 1, 1, 0, 4, 1, 0, 0, 3, 2, 1, 0, 3, 1, 1, 3, 4, 0, 1,
        3, 4, 2, 4, 0, 3, 1, 2, 0, 4, 1, 2, 2, 1, 0, 1, 3, 4, 3, 1, 3, 0,
        0, 2, 2, 1, 3, 4, 2, 0, 0, 1, 1, 3, 0, 0, 4, 2, 4, 3, 3, 0, 3, 4,
        3, 4, 4, 4, 1, 0, 4, 2, 0, 2, 4, 1],
       [1, 0, 2, 4, 4, 0, 4, 1, 4, 1, 0, 2, 3, 1, 2, 4, 4, 2, 2, 0, 1, 2,
        2, 0, 1, 2, 4, 0, 1, 2, 1, 4, 2, 0, 0, 1, 0, 1, 3, 1, 1, 4, 4, 3,
        0, 3, 0, 3, 1, 2, 4, 0, 0, 3, 1, 1, 0, 0, 4, 2, 3, 4, 2, 0, 3, 3,
        1, 2, 4, 3, 0, 0, 4, 2, 4, 2, 0, 3, 0, 0, 4, 2, 1, 0, 4, 3, 0, 1,
        2, 4, 4, 3, 3, 3, 3, 2, 3, 3, 4, 3],
       [2, 4, 4, 0, 3, 3, 0, 3, 1, 0, 2, 2, 2, 0, 2, 1, 4, 0, 4, 4, 1, 3,
        1, 4, 1, 2, 1, 0, 0, 2, 4, 1, 0, 0, 3, 1, 0, 4, 3, 2, 3, 4, 4, 3,
        0, 0, 0, 4, 1, 4, 1, 2, 2, 4, 3, 4, 4, 0, 3, 2, 4, 3, 4, 2, 3, 0,
        2, 1, 3, 2, 0, 1, 4, 1, 3, 3, 1, 2, 0, 2, 4, 0, 2, 4, 3, 4, 3, 0,
        4, 2, 2, 4, 1,

In [29]:
Y = np.array([1, 2, 3, 4, 4, 5])
Y

array([1, 2, 3, 4, 4, 5])

In [ ]:
X,y=datasets.load_iris(return_X_y=True)
# print(X)
# print(y)
X_train=X[range(0,150,2),:]   
y_train=y[range(0,150,2)]
X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]
clf = GaussianNB() #creating instance of a classifier #BernoulliNB() for BernouliNB
#MultinomialNB() for MultinomialNB()
clf.fit(X_train, y_train)
prediction = clf.predict(X_test) #predict using the learnt classifier
print("############### Predictions #################")
print(prediction)
print("#############################################")
print("Accuracy:",metrics.accuracy_score(y_test, prediction, normalize=True))
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

In [ ]:
d_iris(return_X_y=True) #Loading the Iris Dataset
X_train=X[range(0,150,2),:]
y_train=y[range(0,150,2)]
X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]
#variable for specifying number of nearest neighbors to be used
n_neighbors=3
weights='uniform' #or weights='distance'
#creating instance of a classifier
clf = neighbors.KNeighborsClassifier(n_neighbors, weights)
# other argument is metric (default is 'minkowski'. There are many other possibilities including 'euclidean')
#Other useful argument is p which controls the power of minkowski distance. Default is 2
clf.fit(X_train, y_train)
prediction = clf.predict(X_test) #predict using the learnt classifier
print("############### Predictions #################")
print(prediction)
print("#############################################")
print("Accuracy = ", metrics.accuracy_score(y_test, prediction, normalize=True))
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))