# Naive Bayes 


In [2]:
import numpy
from sklearn import datasets, metrics
from sklearn.naive_bayes import GaussianNB
X,y=datasets.load_iris(return_X_y=True)
# print(X)
# print(y)
X_train=X[range(0,150,2),:]   
y_train=y[range(0,150,2)]
X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]
clf = GaussianNB() #creating instance of a classifier #BernoulliNB() for BernouliNB
#MultinomialNB() for MultinomialNB()
clf.fit(X_train, y_train)
prediction = clf.predict(X_test) #predict using the learnt classifier
print("############### Predictions #################")
print(prediction)
print("#############################################")
print("Accuracy:",metrics.accuracy_score(y_test, prediction, normalize=True))
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

############### Predictions #################
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 2 2
 2]
#############################################
Accuracy: 0.96
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

[[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]


# Bernouli


In [22]:
import numpy
from sklearn import datasets, metrics
from sklearn.naive_bayes import GaussianNB


from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd


vectorizer = CountVectorizer()

docs = [ 'Jainil like football',
    'Sports is good for health',
     'Jainil like cricket too',
     'Do you like football?']




vectorizer = CountVectorizer() 
  
vectorizer.fit(docs) 
  
# Printing the identified Unique words along with their indices 
print("Vocabulary: ", vectorizer.vocabulary_) 
  
# Encode the Document 
vector = vectorizer.transform(docs) 
  
# Summarizing the Encoded Texts 
print("Encoded Document is:") 
array = vector.toarray()
print(array)

col_list = [[None] for i in range(0,len(vectorizer.vocabulary_ ) )]


doc_dict = vectorizer.vocabulary_
for key in doc_dict:
    col_list[doc_dict[key]] = key
col_list

df = pd.DataFrame(data = array,columns=col_list)
df


Vocabulary:  {'jainil': 7, 'like': 8, 'football': 2, 'sports': 9, 'is': 6, 'good': 4, 'for': 3, 'health': 5, 'cricket': 0, 'too': 10, 'do': 1, 'you': 11}
Encoded Document is:
[[0 0 1 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 1 1 1 0 0 1 0 0]
 [1 0 0 0 0 0 0 1 1 0 1 0]
 [0 1 1 0 0 0 0 0 1 0 0 1]]


cricket  do  football  for  good  health  is  jainil  like  sports  too  \
0        0   0         1    0     0       0   0       1     1       0    0   
1        0   0         0    1     1       1   1       0     0       1    0   
2        1   0         0    0     0       0   0       1     1       0    1   
3        0   1         1    0     0       0   0       0     1       0    0   

   you  
0    0  
1    0  
2    0  
3    1

In [31]:
print(vector)

  (0, 2)	1
  (0, 7)	1
  (0, 8)	1
  (1, 3)	1
  (1, 4)	1
  (1, 5)	1
  (1, 6)	1
  (1, 9)	1
  (2, 0)	1
  (2, 7)	1
  (2, 8)	1
  (2, 10)	1
  (3, 1)	1
  (3, 2)	1
  (3, 8)	1
  (3, 11)	1


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3) 

In [ ]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()

In [27]:
import numpy as np
rng = np.random.RandomState(1)
X = rng.randint(5, size=(6, 100))
X

array([[3, 4, 0, 1, 3, 0, 0, 1, 4, 4, 1, 2, 4, 2, 4, 3, 4, 2, 4, 2, 4, 1,
        1, 0, 1, 1, 1, 1, 0, 4, 1, 0, 0, 3, 2, 1, 0, 3, 1, 1, 3, 4, 0, 1,
        3, 4, 2, 4, 0, 3, 1, 2, 0, 4, 1, 2, 2, 1, 0, 1, 3, 4, 3, 1, 3, 0,
        0, 2, 2, 1, 3, 4, 2, 0, 0, 1, 1, 3, 0, 0, 4, 2, 4, 3, 3, 0, 3, 4,
        3, 4, 4, 4, 1, 0, 4, 2, 0, 2, 4, 1],
       [1, 0, 2, 4, 4, 0, 4, 1, 4, 1, 0, 2, 3, 1, 2, 4, 4, 2, 2, 0, 1, 2,
        2, 0, 1, 2, 4, 0, 1, 2, 1, 4, 2, 0, 0, 1, 0, 1, 3, 1, 1, 4, 4, 3,
        0, 3, 0, 3, 1, 2, 4, 0, 0, 3, 1, 1, 0, 0, 4, 2, 3, 4, 2, 0, 3, 3,
        1, 2, 4, 3, 0, 0, 4, 2, 4, 2, 0, 3, 0, 0, 4, 2, 1, 0, 4, 3, 0, 1,
        2, 4, 4, 3, 3, 3, 3, 2, 3, 3, 4, 3],
       [2, 4, 4, 0, 3, 3, 0, 3, 1, 0, 2, 2, 2, 0, 2, 1, 4, 0, 4, 4, 1, 3,
        1, 4, 1, 2, 1, 0, 0, 2, 4, 1, 0, 0, 3, 1, 0, 4, 3, 2, 3, 4, 4, 3,
        0, 0, 0, 4, 1, 4, 1, 2, 2, 4, 3, 4, 4, 0, 3, 2, 4, 3, 4, 2, 3, 0,
        2, 1, 3, 2, 0, 1, 4, 1, 3, 3, 1, 2, 0, 2, 4, 0, 2, 4, 3, 4, 3, 0,
        4, 2, 2, 4, 1,

In [29]:
Y = np.array([1, 2, 3, 4, 4, 5])
Y

array([1, 2, 3, 4, 4, 5])

In [ ]:
X,y=datasets.load_iris(return_X_y=True)
# print(X)
# print(y)
X_train=X[range(0,150,2),:]   
y_train=y[range(0,150,2)]
X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]
clf = GaussianNB() #creating instance of a classifier #BernoulliNB() for BernouliNB
#MultinomialNB() for MultinomialNB()
clf.fit(X_train, y_train)
prediction = clf.predict(X_test) #predict using the learnt classifier
print("############### Predictions #################")
print(prediction)
print("#############################################")
print("Accuracy:",metrics.accuracy_score(y_test, prediction, normalize=True))
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

In [ ]:
d_iris(return_X_y=True) #Loading the Iris Dataset
X_train=X[range(0,150,2),:]
y_train=y[range(0,150,2)]
X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]
#variable for specifying number of nearest neighbors to be used
n_neighbors=3
weights='uniform' #or weights='distance'
#creating instance of a classifier
clf = neighbors.KNeighborsClassifier(n_neighbors, weights)
# other argument is metric (default is 'minkowski'. There are many other possibilities including 'euclidean')
#Other useful argument is p which controls the power of minkowski distance. Default is 2
clf.fit(X_train, y_train)
prediction = clf.predict(X_test) #predict using the learnt classifier
print("############### Predictions #################")
print(prediction)
print("#############################################")
print("Accuracy = ", metrics.accuracy_score(y_test, prediction, normalize=True))
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))